### ISSUE TITLE
Access out-of-range

### ISSUE THREAD

**Issue by p-groarke** [marceloclp/bdo-scraper#14]
Parser.js, line ~80 in the while loop. `i` goes out of range on some pages.

You can fix with something along the lines of.

```javascript
			while (++i < children.length) {
				if (children[i].name === 'span') {
					break;
				}
			}

			if (i == children.length) {
				return [];
			}
```

Or whatever pleases you.

edit : You can repro with item `4688`.

**Comment by marceloclp** [comment]
Hey, thanks for letting me know of this error.

I have dropped support for this package and have been solely developing on this other repo https://github.com/marceloclp/calpheonjs
